dist: xenial
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy2.7-6.0
  - pypy3.5

env:
  global:
    - COVERALLS_PARALLEL=true

install:
  - pip install coveralls

script:
  - coverage run --source cheap_repr setup.py test
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
  webhooks: https://coveralls.io/webhook
